weights: yolov5s.pt
cfg: ''
data: data/coco128.yaml
hyp: data/hyps/hyp.scratch.yaml
project: runs/train
name: exp
exist_ok: false
epochs: 2
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
cache_images: false
image_weights: false
multi_scale: false
single_cls: false
adam: false
linear_lr: false
quad: false
workers: 8
label_smoothing: 0.0
entity: null
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
save_dir: runs/train/exp2
